trigger:
- master

variables:
  var1: "Mustafa"
  var2: "Shaik"

pool:
  vmImage: ubuntu-latest

steps:
  - script: echo "Hey $var1 $var2"
    displayName: "Stage-1"

  - script: "Welcome $var1"
    displayName: "stage-2"

    